os: linux
language: python

python:
  - 3.6

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libcairo2-dev libffi-dev

install:
  - pip install -r requirements.txt

script:
  - python validate.py