name: Validate SVG's & build artifact with PNG's

# Triggers (push, pull request and manual)
on:
  push:
  pull_request:
  workflow_dispatch:

# Jobs to run
jobs:
  # Validate
  validate_and_build:
    runs-on: ubuntu-latest
    steps:
      # Environment
      - uses: actions/checkout@v2
        uses: actions/upload-artifact@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      # Dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Generate & validate
      - name: Validate all icons and metadata
        run: python validate.py

      # Upload
      - name: Upload artifact
        with: 
          name: dist
          path: dist