name: Validate SVG's & build artifact with PNG's

# Triggers (push, pull request and manual)
on:
  push:
  pull_request:
  workflow_dispatch:

# Jobs to run
jobs:
  # Validate
  validate_and_build:
    runs-on: ubuntu-latest
    steps:
      # Environment
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      # Dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Generate icons & validate icons
      - name: Validate all icons and metadata
        run: python validate.py

      # Create artifact
      - name: Create artifact
        uses: papeloto/action-zip@v1
        with:
          files: dist/
          dest: icons.zip

      # Create release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./icons.zip
          asset_name: icons.zip
          asset_content_type: application/zip